 runtime: python27
 api_version: 1
 threadsafe: true

 handlers:
 - url: /
   static_files: www/index.html
   upload: www/index.html
   http_headers:
    Access-Control-Allow-Origin: "*"

 - url: /(.*)
   static_files: www/\1
   upload: www/(.*)
   http_headers:
    Access-Control-Allow-Origin: "*"